site_name: Jacobean's K2 Plus firmware
site_description: Documentation for the Creality K2 Plus firmware
site_url: https://jacob10383.github.io/k2-plus-custom-firmware/
repo_url: https://github.com/Jacob10383/k2-plus-custom-firmware

theme:
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.top
    - content.code.copy
    - search.highlight
    - search.suggest
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Use dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Use light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Install: install.md
  - Calibration: calibration.md
  - OrcaSlicer: setup.md
  - CFS and RFID: cfs.md
  - Error explanation: error-explanation.md
  - Updates & Recovery: updates-recovery.md
  - Reference:
      - Command Reference: command-reference.md
      - Config Reference: config-reference.md
